package com.example.graphiql;

import com.example.graphiql.model.Student;
import com.example.graphiql.repository.StudentRepo;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class GraphiqlApplication {

	public static void main(String[] args) {
		SpringApplication.run(GraphiqlApplication.class, args);
	}
	@Bean
	public CommandLineRunner init(StudentRepo repo) {
		return args -> {
			List<Student> s=new ArrayList<>();
			//As id will be autogenerated we have to pass it as null below
			s.add(new Student("adrs1", "Name1", null, "cls1","phn1"));
			s.add(new Student("adrs2", "Name2", null, "cls2","phn2"));
			s.add(new Student("adrs3", "Name3", null, "cls3","phn3"));
			repo.saveAll(s);
		};
	}
}
